import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#5a2d28",
                "inverse-surface": "#362225",
                "primary": "#7a1c28",
                "primary-container": "#4c0f17",
                "surface-container-high": "#f0e3e5",
                "surface-bright": "#faf6f7",
                "on-primary-fixed": "#38060e",
                "on-background": "#231517",
                "primary-fixed-dim": "#f1b3ba",
                "on-primary": "#ffffff",
                "tertiary-container": "#421815",
                "on-secondary-fixed": "#3a1318",
                "secondary": "#9c2a39",
                "outline-variant": "#dcc8ca",
                "on-secondary-container": "#4e1019",
                "tertiary": "#8c443b",
                "error": "#991b1b",
                "tertiary-fixed": "#ffd8d4",
                "on-surface-variant": "#5d4447",
                "on-secondary": "#ffffff",
                "background": "#fdfbfb",
                "on-primary-container": "#f6c8ce",
                "outline": "#8a7073",
                "inverse-primary": "#f8c5cb",
                "secondary-fixed-dim": "#f5b7be",
                "tertiary-fixed-dim": "#e9a79f",
                "on-error": "#ffffff",
                "error-container": "#fee2e2",
                "surface": "#fdfbfb",
                "surface-tint": "#8c2836",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#fde4e7",
                "on-tertiary": "#ffffff",
                "surface-container-highest": "#e8d8da",
                "surface-container": "#f5ebec",
                "on-primary-fixed-variant": "#631721",
                "surface-dim": "#ded0d2",
                "on-error-container": "#7f1d1d",
                "surface-variant": "#ebd9dc",
                "on-tertiary-container": "#f5bcb4",
                "inverse-on-surface": "#fdf5f5",
                "on-surface": "#231517",
                "on-tertiary-fixed": "#370f0b",
                "secondary-fixed": "#fde2e5",
                "on-secondary-fixed-variant": "#6e1d27",
                "secondary-container": "#c94657",
                "surface-container-low": "#faf1f2",
                sipijar: {
                    50: '#fff1f2',
                    100: '#ffe4e6',
                    200: '#fecdd3',
                    300: '#fda4af',
                    400: '#fb7185',
                    500: '#f43f5e',
                    600: '#e11d48',
                    700: '#be123c',
                    800: '#9f1239',
                    900: '#881337',
                    950: '#4c0519',
                }
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem"
            },
            spacing: {
                "margin": "1rem",
                "space-xs": "0.25rem",
                "space-xl": "1.5rem",
                "gutter-tablet": "1.25rem",
                "space-2xs": "0.125rem",
                "space-lg": "1rem",
                "margin-desktop": "2rem",
                "gutter-desktop": "1.5rem",
                "space-3xl": "3rem",
                "space-sm": "0.5rem",
                "margin-tablet": "1.5rem",
                "space-2xl": "2rem",
                "space-md": "0.75rem",
                "gutter": "1rem"
            },
            fontFamily: {
                "body-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "telemetry-data": ["JetBrains Mono", ...defaultTheme.fontFamily.mono],
                "label-md": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-xl": ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "display-lg": ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "body-md": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-sm": ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "body-sm": ["Inter", ...defaultTheme.fontFamily.sans],
                "display-lg-mobile": ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "label-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "caption": ["Inter", ...defaultTheme.fontFamily.sans],
                "telemetry-unit": ["JetBrains Mono", ...defaultTheme.fontFamily.mono]
            },
            fontSize: {
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "telemetry-data": ["24px", { lineHeight: "28px", letterSpacing: "-0.03em", fontWeight: "700" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
                "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
                "headline-lg": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
                "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
                "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
                "caption": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
                "telemetry-unit": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }]
            }
        }
    },
    plugins: [forms, containerQueries],
};
